config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/edit'
  get 'new/edit'
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups, only: [:new, :index, :show, :edit, :create, :update]

  get "search" => "searches#search"

  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :book_tags, dependent: :destroy, foreign_key: 'book_id'
  has_many :tags, through: :book_tags

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5}, presence: true

  is_impressionable

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def save_tags(savebook_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savebook_tags
    new_tags = savebook_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name:new_name)
      self.tags << book_tag
   end
  end


  def self.looks(search, word)
    if search == "perfect_match"
      Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      Book.where("title LIKE?","%#{word}%")
    end
  end

  def self.books_count(day)
    where(created_at: day)
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true

end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, foreign_key: "group_id"
  has_many :users, through: :group_users

  has_one_attached :group_image

  validates :name, presence: true, uniqueness: true

  def get_group_image
    (group_image.attached?)? group_image : 'no_image.jpg'
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :books, through: :book_tags

  scope :merge_books, -> (tags){ }

  def self.looks_tag(search, word)
      Tag.where("name LIKE?", "#{word}")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  has_many :group_users, foreign_key: "user_id"
  has_many :groups, through: :group_users


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    to = Time.current.all_day
    from = (Time.current - 1.day).all_day
    @two = (Time.current - 2.day).all_day
    @three =  (Time.current - 3.day).all_day
    @four =   (Time.current - 4.day).all_day
    @five =   (Time.current - 5.day).all_day
    @six =   (Time.current - 6.day).all_day
    week = Time.current.all_week
    pre_week = (Time.current - 1.week).all_week

    @today_books = @books.books_count(to)
    @yesterday_books = @books.books_count(from)
    @week_books = @books.where(created_at: week)
    @pre_week_books = @books.where(created_at: pre_week)
    @the_day_before = (@today_books.count.to_f / @yesterday_books.count.to_f)*100
    @wow = (@week_books.count.to_f / @pre_week_books.count.to_f ) *100

  end

  def daily_posts
    
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :user_daily_posts_form
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_chart.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">6日前</th>
      <th scope="col">5日前</th>
      <th scope="col">4日前</th>
      <th scope="col">3日前</th>
      <th scope="col">2日前</th>
      <th scope="col">1日前</th>
      <th scope="col">今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @books.books_count(@six).count %></td>
      <td><%= @books.books_count(@five).count %></td>
      <td><%= @books.books_count(@four).count %></td>
      <td><%= @books.books_count(@three).count %></td>
      <td><%= @books.books_count(@two).count %></td>
      <td><%= @yesterday_books.count %></td>
      <td><%= @today_books.count %></td>
    </tr>
  </tbody>
</table>

<canvas id="myChart"></canvas>
<script>
 $(document).on('turbolinks:load', function() {
   var ctx = document.getElementById('myChart');
   var myChart = new Chart(ctx, {
     type: 'line',
     data: {
       labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
       datasets: [{
         label: '投稿した本の数',
         data: [
           <%= @books.books_count(@six).count %>
           <%= @books.books_count(@five).count %>
           <%= @books.books_count(@four).count %>
           <%= @books.books_count(@three).count %>
           <%= @books.books_count(@two).count %>
           <%= @yesterday_books.count %>
           <%= @today_books.count %>
         ],
         borderColor: "rgba(0,0,255,1)",
         backgroundColor: "rgba(0,0,0,0)",
         tension: 0.4
       }],
     },
     options: {
       title: {
         display: true,
         text: '7日間の投稿数の比較'
       },
       responsive: true,
       scales: {
         y:{
           suggestedMin: 0,
           suggestedMax: 10
         },
         x:{
           stacked: true
         },
       },
     }
   });
 });

</script>

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_date_info.html.erb
      <table class="table table-bordered">
       <thead>
         <tr>
           <th scope="col">今日の投稿数</th>
           <th scop="col">前日の投稿数</th>
           <th scop="col">前日比</th>
         </tr>
       </thead>
       <tbody>
         <tr>
           <td><%= @today_books.count %></td>
           <td><%= @yesterday_books.count %></td>
           <td>
             <% if @yesterday_books.count == 0 %>
             　前日の投稿が0のため計算できません
             <% else %>
               <%= @the_day_before.round %> %
             <% end %>
           </td>
         </tr>
       </tbody>
     </table>
           <table class="table table-bordered">
       <thead>
         <tr>
           <th scope="col">今週の投稿数</th>
           <th scop="col">前週の投稿数</th>
           <th scop="col">前週比</th>
         </tr>
       </thead>
       <tbody>
         <tr>
           <td><%= @week_books.count %></td>
           <td><%= @pre_week_books.count %></td>
           <td>
             <% if @pre_week_books.count == 0 %>
              前週の投稿が0のため計算できません
             <% else %>
              <%= @wow.round %> %
             <% end %>
           </td>
         </tr>
       </tbody>
     </table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <% if user.id != current_user.id %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
      <% if user.following?(current_user) %>
        <%= link_to "chatをはじめる", chat_path(user.id), class:"ml-3" %>
      <% end %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
    <% end %>
  <% end %>

</div>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <h2>投稿数の前日比・前週比</h2>
      <%= render 'date_info', books: @books %>
      <h2>7日間分の投稿数</h2>
      <%= render 'book_chart', books: @books %>
    </div>
</div>